codecov:
  require_ci_to_pass: yes
  token: fd215bcb-f033-4e5a-b673-eb68e96921b0

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project: yes
    patch: yes
    changes: no

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: no

ignore:
  - "src/main/java/socket_connection/cryptography/exceptions"  # ignore folders and all its contents